version: '3.8'

services:
  dynamodb:
    build: ./dynamodb
    ports:
      - "8000:8000"

  elasticmq:
    build: ./elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    environment:
      - ELASTICMQ_OPTS=-Dconfig.file=/opt/elasticmq.conf
    volumes:
      - ./elasticmq/elasticmq.conf:/opt/elasticmq.conf

  app:
    build:
      context: .
      dockerfile: nodejs/Dockerfile
    depends_on:
      - dynamodb
      - elasticmq
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - AWS_ACCESS_KEY_ID=accesskey
      - AWS_SECRET_ACCESS_KEY=secretkey
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - SQS_ENDPOINT=elasticmq
      - IS_DOCKER=true