version: '3.8'

services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: orders_tb
      MYSQL_ROOT_PASSWORD: brenno_araujo_root
      MYSQL_USER: brenno_araujo_user
      MYSQL_PASSWORD: brenno_araujo_password
    ports:
      - "3307:3306"
    volumes:
      - ./newdata:/var/lib/mysql
    restart: always

  elasticmq:
    build: ./elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    environment:
      - ELASTICMQ_OPTS=-Dconfig.file=/opt/elasticmq.conf
    volumes:
      - ./elasticmq/elasticmq.conf:/opt/elasticmq.conf

  app:
    build:
      context: .
      dockerfile: nodejs/Dockerfile
    depends_on:
      - elasticmq
      - mysql
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - AWS_ACCESS_KEY_ID=accesskey
      - AWS_SECRET_ACCESS_KEY=secretkey
      - AWS_REGION=us-east-1
      - SQS_ENDPOINT=elasticmq
      - IS_DOCKER=true
      - DB_NAME=orders_tb
      - DB_USER=brenno_araujo_user
      - DB_PASS=brenno_araujo_password
      - DB_HOST=mysql
      - DB_PORT=3306

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.yaml
    volumes:
      - ./swagger:/swagger