service: yandeh-orders-api

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  environment:
    DYNAMODB_TABLE: OrdersTable
    # ORDER_QUEUE_URL: http://localhost:9324/queue/OrderQueue
    ORDER_QUEUE_URL: 'elasticmq-1:9324/queue/OrderQueue'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-offline-sqs

custom:
  serverless-offline:
    httpPort: 3005
    host: '0.0.0.0'
  serverless-offline-sqs:
    autoCreate: true
    endpoint: http://localhost:9324
    region: us-east-1
    queues:
      - name: OrderQueue
        arn:
          Fn::GetAtt:
            - OrderQueue
            - Arn

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
          - AttributeName: clientId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
          - AttributeName: clientId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    OrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: OrderQueue

functions:
  createOrder:
    handler: src/handlers/create-order.handler
    timeout: 30
    # environment:
    #   NODE_ENV: ${env:NODE_ENV}
    #   AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    #   AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    #   AWS_REGION: ${env:AWS_REGION}
    #   DYNAMODB_ENDPOINT: ${env:DYNAMODB_ENDPOINT}
    #   SQS_ENDPOINT: ${env:SQS_ENDPOINT}
    events:
      - http:
          path: orders
          method: post

  importOrders:
    handler: src/handlers/import-orders.handler
    timeout: 30
    # environment:
    #   NODE_ENV: ${env:NODE_ENV}
    #   AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    #   AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    #   AWS_REGION: ${env:AWS_REGION}
    #   DYNAMODB_ENDPOINT: ${env:DYNAMODB_ENDPOINT}
    #   SQS_ENDPOINT: ${env:SQS_ENDPOINT}
    events:
      - http:
          path: orders/import
          method: post

  updateOrderStatus:
    handler: src/handlers/update-order-status.handler
    timeout: 30
    # environment:
    #   NODE_ENV: ${env:NODE_ENV}
    #   AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    #   AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    #   AWS_REGION: ${env:AWS_REGION}
    #   DYNAMODB_ENDPOINT: ${env:DYNAMODB_ENDPOINT}
    #   SQS_ENDPOINT: ${env:SQS_ENDPOINT}
    events:
      - http:
          path: orders/{id}/status
          method: patch

  getOrder:
    handler: src/handlers/get-order.handler
    timeout: 30
    # environment:
    #   NODE_ENV: ${env:NODE_ENV}
    #   AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    #   AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    #   AWS_REGION: ${env:AWS_REGION}
    #   DYNAMODB_ENDPOINT: ${env:DYNAMODB_ENDPOINT}
    #   SQS_ENDPOINT: ${env:SQS_ENDPOINT}
    events:
      - http:
          path: orders
          method: get

  processOrderQueue:
    handler: src/handlers/process-order-queue.handler
    timeout: 30
    # environment:
    #   NODE_ENV: ${env:NODE_ENV}
    #   AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    #   AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    #   AWS_REGION: ${env:AWS_REGION}
    #   DYNAMODB_ENDPOINT: ${env:DYNAMODB_ENDPOINT}
    #   SQS_ENDPOINT: ${env:SQS_ENDPOINT}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - OrderQueue
              - Arn
          batchSize: 5


